inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/brew-cask.rb'
    - 'developer/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Style/BarePercentLiterals:
  EnforcedStyle: percent_q
