language: objective-c
env:
  matrix:
    - CASK_SYSTEM_RUBY_VERSION="1.8"
    - CASK_SYSTEM_RUBY_VERSION="2.0"
    - CASK_SYSTEM_RUBY_VERSION="Current"
before_install:
  - rvm use system
  - PATH="/System/Library/Frameworks/Ruby.framework/Versions/${CASK_SYSTEM_RUBY_VERSION}/usr/bin":"$PATH"
  - brew update
  - brew install cabextract
  - brew install unar
  - sudo /usr/bin/gem install bundler
install:
  - sudo /usr/bin/bundle
script:
  - /usr/bin/bundle exec /usr/bin/rake test
notifications:
  irc:
    channels:
      - "chat.freenode.net#homebrew-cask"
    template:
      - "%{build_number}: %{branch}@%{commit} %{author} -> %{message} %{build_url}"
    use_notice: true
    skip_join: true
  email: false
